// Generated by https://quicktype.io

export interface Crytocurrencies {
  cryptoCurrencies: CryptoCurrency[];
}

export interface CryptoCurrency {
  id: number;
  name: string;
  symbol: string;
  slug: string;
  cmcRank: number;
  numMarketPairs: number;
  circulatingSupply: number;
  totalSupply: number;
  maxSupply: number;
  infiniteSupply: boolean;
  lastUpdated: string;
  dateAdded: string;
  tags: string[];
  platform: Platform | null;
  selfReportedCirculatingSupply: null;
  selfReportedMarketCap: null;
}

export interface Platform {
  id: any[];
  name: any[];
  symbol: any[];
  slug: any[];
  token_address: any[];
}

export interface CustomList {
  id: string;
  name: string;
  userId: string;
  user: null;
  listItemIds: null;
  listItems: any[];
}
